stages:
  - Unit Tests
  - Build Image

unittests:
  image: "python:3.7-buster"

  stage: Unit Tests

  services:
    - name: mariadb
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--character-set-client-handshake=FALSE']
    - name: redis
      alias: redis_queue
    - name: redis
      alias: redis_cache
    - name: redis
      alias: redis_socketio

  variables:
    MYSQL_DATABASE: "test_dodock"
    MYSQL_ROOT_PASSWORD: "test_dodock"

  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-suggests --no-install-recommends mariadb-client
    - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb
    - dpkg -i wkhtmltox_0.12.5-1.buster_amd64.deb && rm wkhtmltox_0.12.5-1.buster_amd64.deb
    - mkdir -p apps
    - mkdir -p apps/frappe
    - mv -f * apps/frappe/ || true
    - mkdir -p sites logs && echo "frappe" > sites/apps.txt
    - mkdir -p ../logs
    - cp -r apps/frappe/test_sites/test_site sites/
    - mkdir -p test_site/logs
    - python -m venv env
    - . env/bin/activate
    - pip3 install --upgrade pip
    - pip3 install --no-cache-dir -e apps/frappe/
    - python apps/frappe/test_sites/test_installer.py || true
    - python apps/frappe/test_sites/test_runner.py


build:
  stage: Build Image

  services:
    - name: docker:19.03.11-dind
      alias: docker

  image: docker

  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  script:
    - docker build -t dodock-worker -f https://gitlab.com/dokos/dokidocker/-/raw/master/build/dodock-worker/Dockerfile .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA