stages:
  - test

unittests:
  image: "python:3.7-buster"

  stage: test

  services:
    - name: mariadb
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--character-set-client-handshake=FALSE']
    - name: redis
      alias: redis_queue
    - name: redis
      alias: redis_cache
    - name: redis
      alias: redis_socketio

  variables:
    MYSQL_DATABASE: "test_dodock"
    MYSQL_ROOT_PASSWORD: "test_dodock"

  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-suggests --no-install-recommends mariadb-client
    - mkdir -p apps
    - mkdir -p apps/frappe
    - mv -f * apps/frappe/ || true
    - mkdir -p sites && echo "frappe" > sites/apps.txt
    - cp -r apps/frappe/test_sites/test_site sites/
    - python -m venv env
    - . env/bin/activate
    - pip3 install --upgrade pip
    - pip3 install --no-cache-dir -e apps/frappe/
    - python apps/frappe/test_sites/test_installer.py || true
    - python apps/frappe/test_sites/test_runner.py