image: "ubuntu:18.04"

variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"

before_script:
  - apt-get update && apt-get install -y curl
  - apt-get update && apt-get install -y wget
  - apt-get update && apt-get install -y python3-minimal
  - apt-get update && apt-get install -y build-essential python-setuptools
  - apt-get update && apt-get install -y sudo
  - adduser --disabled-password --gecos "" dokotest
  - usermod -aG sudo dokotest
  - export LANG=C.UTF-8
  - export LC_ALL=C.UTF-8
  - wget https://gitlab.com/dokos/docli/raw/master/playbooks/install.py
  - python3 install.py --develop --user dokotest --site test_site --run-gitlab-ci --verbose
  - sudo pip install -e ~/bench

stages:
  - Unit Tests

unittests:
  stage: Unit Tests
  script:
    - /home/dokotest/dokos-bench bench --site test_site reinstall --yes
    - /home/dokotest/dokos-bench bench --site test_site scheduler disable
    - /home/dokotest/dokos-bench bench --site test_site run-tests --coverage