image: "ubuntu:18.04"

variables:
  GIT_STRATEGY: none
  GIT_CHECKOUT: "false"

before_script:
  - adduser --disabled-password --gecos "" dokotest
  - usermod -aG sudo dokotest
  - apt-get install -y wget
  - wget https://gitlab.com/dokos/docli/raw/master/playbooks/install.py
  - python3 install.py --production --user dokotest

stages:
  - Unit Tests

unittests:
  stage: Unit Tests
  script:
    - bench --site test_site reinstall --yes
    - bench --site test_site scheduler disable
    - bench --site test_site run-tests --coverage